const FOURSQUARE_URL = 'https://api.foursquare.com/v2/venues';
const CLIENT_ID = 'OA4P10VM0Z34T41FZND1PJP3WWU1C10UYNCFPEYKUU4BX4MG';
const CLIENT_SECRET = '3E2YRHOX0HZDEEYEVEVDOMGAOJJ40RCOCPSF5ICDLTJUB3I5';

export const FOURSQUARE_API_URL = `${FOURSQUARE_URL}/search?client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}`;

 